/**
 * KOL wallet reward pool — one random unclaimed address per campaign clear.
 * Labels are flavor text for the pack reveal (not on-chain verification).
 */

export const KOL_WALLET_POOL = [
  { address: '5GPH7Uq6Rem7PvmGFHavRfL6JVtboszeB4UMBneikA2', label: 'Barron Trump (real)' },
  { address: '2N7qg9a3N6DXgDBXvgZ5JGnXvxUnX1YhBEC5Y7waqxmi', label: 'Barron Trump shitter wallet' },
  { address: '2WfNxFN74pzJWKnXQ7NpkbnbEEhSLVJZGiB9NvxQ4Vpb', label: 'Lizard67' },
  { address: 'E9ouaZGGbKfYdAmHGPrSBeY4GnrSXeLFy3cyUKKJEb8B', label: '0xKitty' },
  { address: 'hJRWEXNPGcjvYyPqttHC4Fba3ZeNDBFkb15E32EwhAR', label: 'ValopaQuant' },
  { address: 'DGmCXVw7kXsgMDSERHwGns46fqtma6ofDyh285rNUaBM', label: 'adamje2' },
  { address: '47cebbaYbJKKeHjrh18r9UMdWiumvyZWiAAvvpmVb3uo', label: 'lj degen' },
  { address: 'EdHb69A1WvL5TSzNxnsousJRSXFUT181iFYirCa4bxEQ', label: 'LLM,insider.' },
  { address: '9B1qWZCx8sPRp2w1K6zo7MFEzzTN51SHxmBQtDQuorsV', label: 'early.LLM' },
  { address: '687kTFNvKG9GXf8UsPzyrKbKpz5ExNrSCWfs7S4PTGiL', label: 'jelly insider' },
  { address: '9zckZP4aqjo8kqLJu2uaig8pZ7yDNmfTBKmjc86F4wfq', label: 'aios2' },
  { address: '8npRxRSgFbzhq2ucJLDpJzmtLqFVmAP5AHAbSmjNJvPD', label: 'aios2' },
  { address: '6ic8Lm4tbV265VzRFhG1ybE7RYHCcbKFBUU6c817w9f4', label: 'chrome2' },
  { address: '3RFnntAiQHab9fohwuPd45Qtko4xowncJL45GtCHrxbg', label: 'whitemenhavingsex.sol' },
  { address: '6EAaPqnwT54YnYfCRyupN8rK25i2hbguBFcbfVQ8hGWj', label: 'vinetoptrader' },
  { address: 'FsMaCLmxF2zEKAQ5CGJMLi49LLjy4vjhjcozmKsLNLK2', label: 'sorkin1' },
  { address: 'AKBRim8GZt5gDVLW6LSqaLKmry2DB4pdGejFquhzHKEu', label: 'Rowdy1' },
  { address: 'HABhDh9zrzf8mA4SBo1yro8M6AirH2hZdLNPpuvMH6iA', label: 'BUGHA (Fortnite nerd trader dude)' },
  { address: '694X5Cuvx6xs4y2aDBu5U1RkZS4RTbcUCZ8qLbH7bVPc', label: 'illadelph.factories' },
  { address: 'G9RpyHTazmaiji5cbWwH3CYEpN1TqbibxtZ1S6KTt6ne', label: 'REQ.1' },
  { address: '6ocX9nqdTLjm99HXXFVfucshcvWVo7h8BFQDwk9R12xu', label: 'CRY 1' },
  { address: 'HUddtYB3iJKW57AaRqZa4JpJ15Tm7rbYqJJwGttneDWz', label: 'vine1' },
  { address: '3kXhcEUW8fEeASzJwanqQwpScS2vF7fkZYzNUNh4t1rC', label: 'vine.deez.nuts.4' },
  { address: '3xqUaVuAWsppb8yaSPJ2hvdvfjteMq2EbdCc3CLguaTE', label: 'vine.5' },
  { address: '4WrdjxxJ13AbxuY6JJwGWfoxD2tUE1X4TBSRfTAGdTTA', label: 'vine insidor 6' },
  { address: 'BLhQ4fWgkNAJ4MWXSdXaTnxwZxwHh7QTnMQb6i3Z2QYy', label: 'qwerty1' },
  { address: '2huXTbjeBhtMZ1ugNwUGucYBRasRaaiypymUX6P1Kwjx', label: 'melania4' },
  { address: 'Bpk7VVctpzXYx4BuPnZzs3VSSAWSAQJVq9VufFAq5p6b', label: 'marqus2' },
  { address: '88JhBphqeZT3SYkHbD3AkpM1omQQpGimvFE92EbsL7Jh', label: 'shakey6' },
  { address: '3bMMdAVdXfVNqNcSH2YkaCBq3G3rL6hVLYnZz5Nfefbx', label: 'perc' },
  { address: '9zPxrXcor3gzTsg73LGBji6VVpfNYeiAq9T9GDPmKTHV', label: 'ZEREBRO' },
  { address: '3JPYL9xEPFjefV3tccrUwhLzME1mMq2dQSDeDebgzQi6', label: 'binance5' },
  { address: '6b8ydf4wnrYe66VmwhEmvGhfWvzLv8Ce5b57MGoVWWKe', label: 'binance4' },
  { address: 'BDhpEzHgS2TQ7Y8Dmz6dwhAd6i5FZqHycV6TiqaxViC4', label: 'binance3' },
  { address: '7oQEAt41V1jCYShRC3s3rfrZyPfG421QXPpwB2G2qVek', label: 'binance2' },
  { address: 'BXvikrCePUMXyrvTvyyp3jddzL3KNvcJELQcET5eBFkh', label: 'Binance1' },
  { address: '6YUFLFC71aipfWijKgnWBaZABxwU9x5g4kqnZMVrMAgg', label: 'Goldenbull' },
  { address: '4oS8HfZrHLBo25svW7cY9GSqLEUG4GPutGpPWJpCzH9P', label: 'Alpha2' },
  { address: '45yBcpnzFTqLYQJtjxsa1DdZkgrTYponCg6yLQ6LQPu6', label: 'Pesto.buy.early' },
  { address: 'Ay9wnuZCRTceZJuRpGZnuwYZuWdsviM4cMiCwFoSQiPH', label: 'hexie' },
  { address: '22hQSTCXbgQdVVEUWBaHqZGwXuu18mnSp5jbrLvQzcxK', label: 'grower' },
  { address: 'EbNr5s54pCUFzEyBDjJWwqYQc7R5E8udmPEpDLwpbjKq', label: 'HYUMMM' },
  { address: 'CNudZYFgpbT26fidsiNrWfHeGTBMMeVWqruZXsEkcUPc', label: 'binance69' },
  { address: 'HXkP2HJ3436u1urLnLsupqjtX1647bA2TtcHNWiDt49U', label: 'voyage1' },
  { address: '2agaMheSNynMBqABpxvoFSAt4MBD5TFLNJuihiepNnjr', label: 'gammaVOYAGE' },
  { address: 'GG2TmwJf8zkfwSFgZxbXuaAhTHbk5U6UwXv4xEEJwzsD', label: 'deltaVOYAGE' },
  { address: 'ECMvT4GQ59aWQVidtzarfvSr7vaZZUnvi1SvaurmtLRD', label: 'voyage5' },
  { address: 'wUdmee42EZcGxYfJdz1tTyyubUitjd7khhgaPWNrosh', label: 'griffainINSIDER' },
  { address: 'XMAmv7f956LoUtqQc7CvLnfCgiMFedkr3Npxy9T7mAy', label: 'nain' },
  { address: 'BR1VVREkrcUvrNGjSYGgy1zcN13dR6rX57AbSqgAY1xQ', label: 'Vaylin2' },
  { address: 'HS7RA5xXJSzLRBpGXRPbm9GwFyPoyHq9iS7wP1k8Houf', label: 'DEV 2' },
  { address: '6yzmcnrB5YGrCcyE9JDVwKeVRWRBPoscmpYshkyYYBA7', label: 'MOSTACHE QUANT 1' },
  { address: 'AMUYbW66jWJFmuWZDsLT7nuGoi5v94su2aqWHknqMZZP', label: 'DURANT 1' },
  { address: 'fwHknyxZTgFGytVz9VPrvWqipW2V4L4D99gEb831t81', label: 'PowWhale' },
  { address: 'HW2WU2i93vTFurADDyoq6dFNL7ai8CefKMQUBxXUhQqE', label: 'whale3' },
  { address: '9Tq6qJMmuibA7tqRy486doX7AhtnDTftWjffDmia8V2g', label: 'UbeendesHOKD' },
  { address: 'HYWo71Wk9PNDe5sBaRKazPnVyGnQDiwgXCFKvgAQ1ENp', label: 'Ansems ALT' },
  { address: 'DfMxre4cKmvogbLrPigxmibVTTQDuzjdXojWzjCXXhzj', label: 'Pulsr Delta' },
  { address: '6T8Yr9DUUS2R8GHevaeaZcoxA1Jku51ZBkmcM7NaZiNE', label: 'Stargate 2insider' },
  { address: 'GeZHejJJJ7631AHAaoEfSmmL7CwhRNPH81FkawEfN7N9', label: 'Slownsteady' },
  { address: '8fSnLTnRViK83dDesivTsPx2wiRhwti9xoafeMGjEyLJ', label: 'Goblin1' },
  { address: 'RFSqPtn1JfavGiUD4HJsZyYXvZsycxf31hnYfbyG6iB', label: 'Kippits' },
  { address: 'CBaM2xaPdDdhaopd8dD93LJAvextJoPngdKFz8QFP7JD', label: 'Shadow' },
  { address: 'HtucFepgUkMpHdrYsxMqjBNN6qVBdjmFaLZneNXopuJm', label: 'Orangie friend 2' },
  { address: '8deJ9xeUvXSJwicYptA9mHsU2rN2pDx37KWzkDkEXhU6', label: 'Cooker 2' },
  { address: '9yYya3F5EJoLnBNKW6z4bZvyQytMXzDcpU5D6yYr4jqL', label: 'PythiaX1' },
  { address: '215nhcAHjQQGgwpQSJQ7zR26etbjjtVdW74NLzwEgQjP', label: 'ANT' },
  { address: '8MaVa9kdt3NW4Q5HyNAm1X5LbR8PQRVDc1W8NMVK88D5', label: 'Daumen' },
  { address: 'FrQ59KmKUhu8G3KnDz5sDQzhnqPGBn41WSM3EN634J3S', label: 'Amrxell' },
  { address: 'HdxkiXqeN6qpK2YbG51W23QSWj3Yygc1eEk2zwmKJExp', label: 'Goat realis whale' },
  { address: 'A4DCAjDwkq5jYhNoZ5Xn2NbkTLimARkerVv81w2dhXgL', label: 'Pow side (coyote1)' },
  { address: '4fxpWbsubzCYqHvQFtAGETa4zqm1PZeqq8TVUCUnhmeJ', label: 'KOL operative' },
  { address: 'AUqA1tni7ZL5iV3eMn3MGqph5encRAaYg1bvocKDLKf3', label: 'Adam Sandler.sol' },
  { address: '3c83ZDYttgEWx9dCchCWHxd37UwuApupj5jAogYfSdyt', label: 'Verysmart' },
  { address: '5CP6zv8a17mz91v6rMruVH6ziC5qAL8GFaJzwrX9Fvup', label: 'Fric2' },
  { address: '8CZjFG1EV3FduGV918QWUh7fevUoZSTffVY8bK6M3wbu', label: 'Pretty good' },
  { address: 'CA4keXLtGJWBcsWivjtMFBghQ8pFsGRWFxLrRCtirzu5', label: 'Sensei' },
  { address: 'G5nxEXuFMfV74DSnsrSatqCW32F34XUnBeq3PfDS7w5E', label: 'LebronJRSol' },
  { address: 'HmBmSYwYEgEZuBUYuDs9xofyqBAkw4ywugB1d7R7sTGh', label: 'Es' },
  { address: 'PhsAGhZV3HYeFzTi44g2qGubs9pxJRMYptDdPRXstpF', label: 'feeds walet' },
  { address: '91eE34Ct5Kyon7SuFYAh7ouebpTX5CZ9mH22piMDRb6A', label: 'kenpach' },
  { address: 'BC8yiFFQWFEKrEEj75zYsuK3ZDCfv6QEeMRif9oZZ9TW', label: 'KOL operative' },
  { address: 'DqrTpRqgiEE5GKePgYkhRyR2Vx9XnSJrV1Jd3ZZVECLF', label: 'KOL operative' },
  { address: 'TimeAdRpWxqKXR5YPEwGBF48KC5V5TxB2g6mnyCp4VR', label: 'orangie' },
  { address: '8rvAsDKeAcEjEkiZMug9k8v1y8mW6gQQiMobd89Uy7qR', label: 'casino 1' },
  { address: 'F9meywQee74tqAKQvDb4Q9bon7y2XLNwUyFYUNEQUto9', label: 'buttcoinalpha' },
  { address: '286CHN57Km41GsAnDv866WKd6YB6HPSjFgF4rGDJTRLf', label: 'useless fucking whale' },
  { address: 'BX1wTJKC6LC1shid4GiD7qVyGQmoce1ryfGRfU9tUegZ', label: 'solid testing' },
  { address: 'DzDemJNZkNFZDCFYGtnmBUUWcFWF8hLBTMWpFtD1VYaj', label: 'UberMendes' },
  { address: 'E57hYjjwNAnvXe67C1q7nKRdC2jWMRGLWAJsBJAJrgzR', label: 'ripper' },
  { address: '6QSc2CxSdkUQSXttkceR9yMuxMf36L75fS8624wJ9tXv', label: 'fric4' },
  { address: 'AGWVu9izo9T2nb3rTBnHDq4WaeHK3Z68PbN2bAaUnPE9', label: 'Jack.herrer' },
  { address: 'BTZJRdccNMrF1tdwjSk9K369udDJpk8mxrZNP2U7vAxY', label: 'KOL operative' },
  { address: 'J6TDXvarvpBdPXTaTU8eJbtso1PUCYKGkVtMKUUY8iEa', label: 'KOL operative' },
  { address: '7aMgK5L4qEQ8Nyv6ZzhZi2B82NSSRnwb2NGJnNagA46D', label: 'StandNeet TT alpha' },
  { address: '3BLjRcxWGtR7WRshJ3hL25U3RjWr5Ud98wMcczQqk4Ei', label: 'sebastian' },
  { address: '87rRdssFiTJKY4MGARa4G5vQ31hmR7MxSmhzeaJ5AAxJ', label: 'DIOR' },
  { address: '4uFBc9dmLrMQkD5BYXVYMYJ5iUsQ8dKG3kiWx8pxrR7G', label: 'Aura1' },
  { address: '3kebnKw7cPdSkLRfiMEALyZJGZ4wdiSRvmoN4rD1yPzV', label: 'Bastille' },
  { address: '6mWEJG9LoRdto8TwTdZxmnJpkXpTsEerizcGiCNZvzXd', label: 'LMAO' },
  { address: '6Bp46XwCKpqRKeGrbdeqeU7aVSRRvgiArQ67GEhK3wHz', label: 'AURA6' },
  { address: 'GjkmU5nYM77nxSUdZyUQzf8X7f8tqgotLAYUrK7DJter', label: "Itai's side wallet possibly" },
  { address: '43sautaLiSs6ekDio577fRmcbfrhHzt4GSJd2pZD24Vh', label: 'Fud Reaper' },
  { address: 'DAEdBmTPEKM6xkwfzC3d411QUe6coKpkND6UURa4CvHC', label: 'KOL operative' }
];
